name: Build project and run Lighthouse CI
on: [push, pull_request]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run npm install
        run: |
          npm install --prefix monorepo-ci-space/
      - name: Run Lighthouse CI and Budgets
        run: |
          npm install -g @lhci/cli@0.6.1
          lhci autorun --config monorepo-ci-space/lighthouse/lighthouserc-app1.js && lhci assert --no-lighthouserc --budgetsFile=./monorepo-ci-space/lighthouse/budget.json
          lhci autorun --config monorepo-ci-space/lighthouse/lighthouserc-app2.js && lhci assert --no-lighthouserc --budgetsFile=./monorepo-ci-space/lighthouse/budget.json
      - name: Upload Reports
        if: github.event.pull_request.closed == true
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: "lighthouse-ci-reports"
          AWS_ACCESS_KEY_ID: ${{ secrets.LIGHTHOUSE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LIGHTHOUSE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "./lh/reports"
          DEST_DIR: "$(date +'%s')"