name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install --prefix monorepo-ci-space/
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.1
          lhci autorun --config monorepo-ci-space/lighthouserc.js || echo "LHCI failed!"
      - name: Upload Reports
        uses: shallwefootball/s3-upload-action@v1.1.3
        with:
          source_dir: /tmp/reports
          destination_dir: ''
          aws_key_id: ${{ secrets.LIGHTHOUSE_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.LIGHTHOUSE_AWS_SECRET_ACCESS_KEY }}
          aws_bucket: lighthouse-ci-reports